showTodos:
  path: /
  controller: App\Controller\TodosController::showTodos
  methods: [GET, HEAD]

showCompleteTodos:
  path: /complete/all
  controller: App\Controller\TodosController::showCompletedTodos
  methods: [GET, HEAD]

completeTodo:
  path: /complete/{id}
  controller: App\Controller\TodosController::completeTodo
  methods: [GET, HEAD]

uncompleteTodo:
  path: /uncomplete/{id}
  controller: App\Controller\TodosController::uncompleteTodo
  methods: [GET, HEAD]
